// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThueDat.Data.EF;

#nullable disable

namespace QuanLyThueDat.Data.Migrations
{
    [DbContext(typeof(QuanLyThueDatDbContext))]
    [Migration("20230427072741_Initial14")]
    partial class Initial14
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfig", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRole", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.CanBo_QuyetDinhThueDat", b =>
                {
                    b.Property<int>("IdCanBo_QuyetDinhThueDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCanBo_QuyetDinhThueDat"), 1L, 1);

                    b.Property<string>("CanBo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCanBoQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<string>("TenDoanhNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCanBo_QuyetDinhThueDat");

                    b.ToTable("CanBo_QuyetDinhThueDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.DoanhNghiep", b =>
                {
                    b.Property<int>("IdDoanhNghiep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoanhNghiep"), 1L, 1);

                    b.Property<string>("CoQuanQuanLyThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDoanhNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDoanhNghiep");

                    b.ToTable("DoanhNghiep", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.Files", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFile"), 1L, 1);

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFile");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.FileTaiLieu", b =>
                {
                    b.Property<int>("IdFileTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFileTaiLieu"), 1L, 1);

                    b.Property<int>("IdFile")
                        .HasColumnType("int");

                    b.Property<int>("IdLoaiTaiLieu")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTaiLieu")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiTaiLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdFileTaiLieu");

                    b.HasIndex("IdFile")
                        .IsUnique();

                    b.ToTable("FileTaiLieu", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.HopDongThueDat", b =>
                {
                    b.Property<int>("IdHopDongThueDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHopDongThueDat"), 1L, 1);

                    b.Property<string>("CoQuanKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLucHopDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLucHopDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKyHopDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHopDongDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHopDongThueDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("HopDongThueDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.PhuongXa", b =>
                {
                    b.Property<int>("IdPhuongXa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhuongXa"), 1L, 1);

                    b.Property<int>("IdQuanHuyen")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuongXa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPhuongXa");

                    b.HasIndex("IdQuanHuyen");

                    b.ToTable("PhuongXa", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuanHuyen", b =>
                {
                    b.Property<int>("IdQuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuanHuyen"), 1L, 1);

                    b.Property<string>("TenQuanHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuanHuyen");

                    b.ToTable("QuanHuyen", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhDonGiaThueDat", b =>
                {
                    b.Property<int>("IdQuyetDinhDonGiaThueDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyetDinhDonGiaThueDat"), 1L, 1);

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuyetDinhDonGiaThueDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("QuyetDinhDonGiaThueDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhGiaoDat", b =>
                {
                    b.Property<int>("IdQuyetDinhGiaoDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyetDinhGiaoDat"), 1L, 1);

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DoanhNghiepIdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuyetDinhGiaoDat");

                    b.HasIndex("DoanhNghiepIdDoanhNghiep");

                    b.ToTable("QuyetDinhGiaoDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhGiaoLaiDat", b =>
                {
                    b.Property<int>("IdQuyetDinhGiaoLaiDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyetDinhGiaoLaiDat"), 1L, 1);

                    b.Property<decimal>("DienTichKhongPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DienTichPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongDienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("ViTriThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuyetDinhGiaoLaiDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("QuyetDinhGiaoLaiDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhMienTienThueDat", b =>
                {
                    b.Property<int>("IdQuyetDinhMienTienThueDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyetDinhMienTienThueDat"), 1L, 1);

                    b.Property<decimal>("DienTichMienTienThueDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLucMienTienThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLucMienTienThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhMienTienThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhMienTienThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhMienTienThueDatDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyetDinhMienTienThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanMienTienThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuyetDinhMienTienThueDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("QuyetDinhMienTienThueDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhThueDat", b =>
                {
                    b.Property<int>("IdQuyetDinhThueDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyetDinhThueDat"), 1L, 1);

                    b.Property<DateTime?>("DenNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChiThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPhuongXa")
                        .HasColumnType("int");

                    b.Property<int>("IdQuanHuyen")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MucDichSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhGiaoDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhGiaoDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhGiaoDatDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhThueDatDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyetDinhGiaoDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongDienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TuNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTriThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuyetDinhThueDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("QuyetDinhThueDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhThueDatChiTiet", b =>
                {
                    b.Property<int>("IdQuyetDinhThueDatChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyetDinhThueDatChiTiet"), 1L, 1);

                    b.Property<DateTime?>("DenNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<string>("MucDichSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TuNgayThue")
                        .HasColumnType("datetime2");

                    b.HasKey("IdQuyetDinhThueDatChiTiet");

                    b.HasIndex("IdQuyetDinhThueDat");

                    b.ToTable("QuyetDinhThueDatChiTiet", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoDonGiaThueDat", b =>
                {
                    b.Property<int>("IdThongBaoDonGiaThueDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBaoDonGiaThueDat"), 1L, 1);

                    b.Property<DateTime?>("DenNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChiThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DienTichKhongPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DienTichPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<int?>("IdHopDongThueDat")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<int?>("IdQuyetDinhThueDatChiTiet")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LanThongBaoDonGiaThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanhDaoKyThongBaoDonGiaThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLucDonGiaThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLucDonGiaThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThongBaoDonGiaThueDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoThongBaoDonGiaThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThongBaoDonGiaThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanDonGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongDienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TuNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTriThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThongBaoDonGiaThueDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("ThongBaoDonGiaThueDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoGhiThuGhiChi", b =>
                {
                    b.Property<int>("IdThongBaoGhiThuGhiChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBaoGhiThuGhiChi"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThongBaoGhiThuGhiChi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungGhiChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungGhiThu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoThongBaoGhiThuGhiChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienGhiChi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienGhiThu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdThongBaoGhiThuGhiChi");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("ThongBaoGhiThuGhiChi", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoTienSuDungDat", b =>
                {
                    b.Property<int>("IdThongBaoTienSuDungDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBaoTienSuDungDat"), 1L, 1);

                    b.Property<DateTime?>("DenNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChiThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DienTichKhongPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DienTichPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<int?>("IdHopDongThueDat")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<int?>("IdQuyetDinhThueDatChiTiet")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LanThongBaoTienSuDungDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanhDaoKyThongBaoTienSuDungDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoBoiThuongGiaiPhongMatBang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoMienGiam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHieuLucTienSuDungDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHieuLucTienSuDungDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThongBaoTienSuDungDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoThongBaoTienSuDungDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienBoiThuongGiaiPhongMatBang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienMienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThongBaoTienSuDungDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanDonGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongDienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TuNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTriThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThongBaoTienSuDungDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("ThongBaoTienSuDungDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoTienThueDat", b =>
                {
                    b.Property<int>("IdThongBaoTienThueDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBaoTienThueDat"), 1L, 1);

                    b.Property<int>("BiDieuChinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DenNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChiThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DienTichKhongPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DienTichPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDoanhNghiep")
                        .HasColumnType("int");

                    b.Property<int?>("IdHopDongThueDat")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdQuyetDinhMienTienThueDat")
                        .HasColumnType("int");

                    b.Property<int?>("IdQuyetDinhThueDat")
                        .HasColumnType("int");

                    b.Property<int?>("IdQuyetDinhThueDatChiTiet")
                        .HasColumnType("int");

                    b.Property<int?>("IdThongBaoDonGiaThueDat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LanhDaoKyThongBaoTienThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThongBaoTienThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDichSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThongBaoDonGiaThueDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThongBaoTienThueDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoThongBaoDonGiaThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoThongBaoTienThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienMienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenQuyetDinhThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThongBaoDonGiaThueDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongDienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TuNgayThue")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTriThuaDat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThongBaoTienThueDat");

                    b.HasIndex("IdDoanhNghiep");

                    b.ToTable("ThongBaoTienThueDat", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoTienThueDatChiTiet", b =>
                {
                    b.Property<int>("IdThongBaoTienThueDatChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBaoTienThueDatChiTiet"), 1L, 1);

                    b.Property<DateTime?>("DenNgayTinhTien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DienTichKhongPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DienTichPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdThongBaoDonGiaThueDat")
                        .HasColumnType("int");

                    b.Property<int>("IdThongBaoTienThueDat")
                        .HasColumnType("int");

                    b.Property<int?>("IdThongBaoTienThueDatGoc")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienMienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienPhaiNop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TuNgayTinhTien")
                        .HasColumnType("datetime2");

                    b.HasKey("IdThongBaoTienThueDatChiTiet");

                    b.HasIndex("IdThongBaoTienThueDat");

                    b.ToTable("ThongBaoTienThueDatChiTiet", (string)null);
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.FileTaiLieu", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.Files", "File")
                        .WithOne("FileTaiLieu")
                        .HasForeignKey("QuanLyThueDat.Data.Entities.FileTaiLieu", "IdFile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.HopDongThueDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsHopDongThueDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.PhuongXa", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("DsPhuongXa")
                        .HasForeignKey("IdQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhDonGiaThueDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsQuyetDinhDonGiaThueDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhGiaoDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", null)
                        .WithMany("DsQuyetDinhGiaoDat")
                        .HasForeignKey("DoanhNghiepIdDoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhGiaoLaiDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsQuyetDinhGiaoLaiDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhMienTienThueDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsQuyetDinhMienTienThueDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhThueDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsQuyetDinhThueDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhThueDatChiTiet", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.QuyetDinhThueDat", "QuyetDinhThueDat")
                        .WithMany("DsQuyetDinhThueDatChiTiet")
                        .HasForeignKey("IdQuyetDinhThueDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuyetDinhThueDat");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoDonGiaThueDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsThongBaoDonGiaThueDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoGhiThuGhiChi", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsThongBaoGhiThuGhiChi")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoTienSuDungDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsThongBaoTienSuDungDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoTienThueDat", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DsThongBaoTienThueDat")
                        .HasForeignKey("IdDoanhNghiep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoTienThueDatChiTiet", b =>
                {
                    b.HasOne("QuanLyThueDat.Data.Entities.ThongBaoTienThueDat", "ThongBaoTienThueDat")
                        .WithMany("DsThongBaoTienThueDatChiTiet")
                        .HasForeignKey("IdThongBaoTienThueDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThongBaoTienThueDat");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.DoanhNghiep", b =>
                {
                    b.Navigation("DsHopDongThueDat");

                    b.Navigation("DsQuyetDinhDonGiaThueDat");

                    b.Navigation("DsQuyetDinhGiaoDat");

                    b.Navigation("DsQuyetDinhGiaoLaiDat");

                    b.Navigation("DsQuyetDinhMienTienThueDat");

                    b.Navigation("DsQuyetDinhThueDat");

                    b.Navigation("DsThongBaoDonGiaThueDat");

                    b.Navigation("DsThongBaoGhiThuGhiChi");

                    b.Navigation("DsThongBaoTienSuDungDat");

                    b.Navigation("DsThongBaoTienThueDat");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.Files", b =>
                {
                    b.Navigation("FileTaiLieu");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuanHuyen", b =>
                {
                    b.Navigation("DsPhuongXa");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.QuyetDinhThueDat", b =>
                {
                    b.Navigation("DsQuyetDinhThueDatChiTiet");
                });

            modelBuilder.Entity("QuanLyThueDat.Data.Entities.ThongBaoTienThueDat", b =>
                {
                    b.Navigation("DsThongBaoTienThueDatChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
